Create Flat button grid component
pulsarml/ui.react.components pull request #5
Opened 2022-02-01 16:51 UTC by tanweer919

2022-02-02 14:25 UTC, silvanojulio requested changes
In case the component does not require more functionality (icons, setting the background color, etc...) this is OK.

2022-02-02 14:25 UTC, silvanojulio commented on src/components/FlatButtonGrid/index.tsx
> +    <div className={classes.flatButtonGrid}>
please, use classes.root instead of classes.flatButtonGrid.

2022-02-02 14:26 UTC, silvanojulio commented on src/components/FlatButtonGrid/index.tsx
> +  items: String[];
The component should receive classNames to merge it with the root style

2022-02-03 15:38 UTC, tanweer919 commented on src/components/FlatButtonGrid/index.tsx
> +        <div className={classes.gridItem}>{item}</div>
done

2022-02-03 15:38 UTC, tanweer919 commented on src/components/FlatButtonGrid/index.tsx
> +    <div className={classes.flatButtonGrid}>
done

2022-02-03 15:38 UTC, tanweer919 commented on src/components/FlatButtonGrid/index.tsx
> +  items: String[];
done

2022-02-03 17:17 UTC, silvanojulio approved these changes

2022-02-03 21:08 UTC, merged